# ──────────────────────────────────────────────────────────────────────────────
# FILE: app/ui/pdf_generator.py
# PURPOSE: Generates a formatted PDF report from the daily slang list.
#
# BANGLISH NOTE:
#   Bengali field uses Banglish (romanized Bengali) instead of Bengali script.
#   This works with any standard font and renders correctly in all PDF viewers
#   and terminals without needing special fonts or text shaping engines.
#
# HOW IT CONNECTS:
#   → Called by pdf_node in app/agent/nodes.py
#   → Receives List[SlangWord] from the state
#   → Saves to outputs/pdfs/YYYY-MM-DD.pdf
# ──────────────────────────────────────────────────────────────────────────────

from pathlib import Path
from datetime import datetime

from fpdf import FPDF


PDF_DIR = Path("outputs/pdfs")


def generate_pdf(slangs) -> Path:
    """Generates a clean PDF report and saves it to outputs/pdfs/YYYY-MM-DD.pdf."""

    PDF_DIR.mkdir(parents=True, exist_ok=True)

    today = datetime.now().strftime("%Y-%m-%d")
    file_path = PDF_DIR / f"{today}.pdf"

    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", style="B", size=20)
    pdf.set_text_color(26, 26, 46)
    pdf.cell(0, 10, "Daily Slang Matrix", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(136, 136, 136)
    pdf.cell(0, 6, f"Generated on {today}  |  {len(slangs)} words", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(6)

    # ── One block per slang ───────────────────────────────────────────────────
    for i, slang in enumerate(slangs, 1):

        pdf.set_font("Helvetica", style="B", size=13)
        pdf.set_text_color(22, 33, 62)
        pdf.multi_cell(0, 7, f"{i}. {slang.word}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", size=10)
        pdf.set_text_color(85, 85, 85)
        pdf.multi_cell(0, 6, f"Meaning  : {slang.meaning}", new_x="LMARGIN", new_y="NEXT")

        pdf.multi_cell(0, 6, f"Banglish : {slang.bengali}", new_x="LMARGIN", new_y="NEXT")

        pdf.multi_cell(0, 6, f"Tone     : {slang.tone}", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", style="I", size=10)
        pdf.set_text_color(68, 68, 68)
        pdf.multi_cell(0, 6, slang.example, new_x="LMARGIN", new_y="NEXT")

        pdf.ln(2)
        pdf.set_draw_color(230, 230, 230)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(4)

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(170, 170, 170)
    pdf.cell(0, 6, "Generated by Daily Slang Matrix - Single Agent RAG System", align="C")

    pdf.output(str(file_path))
    return file_path
